service: unzip-s3

useDotenv: true
frameworkVersion: '3'

provider:
  name: aws
  runtime: go1.x
  memorySize: 512

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "s3:GetObject"
            - "s3:PutObject"
          Resource:
            - 'arn:aws:s3:::${env:UNZIP_BUCKET}/*'

package:
  patterns:
    - '!./**'
    - ./bin/**

functions:
  unzip:
    handler: bin/unzip
    timeout: 100
    events:
      - s3:
          bucket: ${env:UNZIP_BUCKET}
          event: s3:ObjectCreated:*
          rules:
            - suffix: .zip
